# Generated by Django 3.1.7 on 2021-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210304_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hall',
            field=models.CharField(choices=[('Daniel', 'Daniel'), ('Abraham', 'Abraham'), ('Joseph', 'Joseph'), ('Isaac', 'Isaac'), ('Dorcas', 'Dorcas'), ('Sarah', 'Sarah'), ('Abigail', 'Abigail')], default='Daniel', max_length=20, verbose_name='Hall'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], default='100', max_length=3, verbose_name='Level'),
        ),
    ]
