# Generated by Django 3.1.7 on 2021-03-05 01:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210304_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.CharField(blank=True, max_length=4, validators=[core.validators.validate_room], verbose_name='Room Number'),
        ),
    ]
