# Generated by Django 3.1.7 on 2021-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210305_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Learn More',
            },
        ),
    ]
