# Generated by Django 3.1.7 on 2021-03-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_link',
            field=models.URLField(default=''),
        ),
    ]
