# Generated by Django 3.1.7 on 2021-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_ref',
        ),
        migrations.AddField(
            model_name='rafflecampaign',
            name='ticket_price',
            field=models.FloatField(default=500.0),
        ),
    ]
