# Generated by Django 3.1.7 on 2021-03-05 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draw', '0002_auto_20210305_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='campaign',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='draw.rafflecampaign'),
        ),
    ]
