# Generated by Django 3.1.7 on 2021-03-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20210305_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRaffleCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draw.rafflecampaign')),
            ],
        ),
    ]
