# Generated by Django 3.1.7 on 2021-03-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_activerafflecampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activerafflecampaign',
            options={'verbose_name_plural': 'Active Raffle Campaign'},
        ),
        migrations.AddField(
            model_name='rafflecampaign',
            name='prizes',
            field=models.ManyToManyField(null=True, to='draw.Prize'),
        ),
    ]
