# Generated by Django 3.1.7 on 2021-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_upcomingrafflecampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafflecampaign',
            name='ticket_price',
            field=models.FloatField(default=200.0),
        ),
    ]
