# Generated by Django 3.1.7 on 2021-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_auto_20210316_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflecampaign',
            name='winner_announced',
            field=models.BooleanField(default=False),
        ),
    ]
