# Generated by Django 3.1.7 on 2021-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_auto_20210317_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerafflecampaign',
            name='visible_countdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upcomingrafflecampaign',
            name='visible_countdown',
            field=models.BooleanField(default=True),
        ),
    ]
