# Generated by Django 3.1.7 on 2021-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_auto_20210317_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafflecampaign',
            name='winning_ticket',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
